services:
  # A Web Service for our Python Flask application
  - type: web
    name: youtube-downloader
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    # THE FIX: Use an eventlet worker for Socket.IO
    startCommand: "gunicorn --worker-class eventlet -w 1 server:app"
    buildpacks:
      - url: https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest